#!/usr/bin/env bash
#Install nginx web server
apt-get -y update
apt-get -y install nginx
systemctl start nginx
# sed -i 's/listen [0-9]+/listen 80/' /etc/nginx/sites-available/default
# sed -i 's/listen \[::\]:[0-9]+/listen \[::\]:80/' /etc/nginx/sites-available/default
echo "Holberton School for the win!" | tee /var/www/html/index.nginx-debian.html > /dev/null
systemctl restart nginx
