#!/usr/bin/env bash
# Configure nginx web server with custom response header

# shellcheck disable=SC2154

# config custom response header
sudo sed -i '/^\slocation.*/i \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# run server
sudo service nginx start
