#!/usr/bin/env bash
# Display text in infinte loop
i=1
ps | tail -n 1 | cut -d ' ' -f 1 | sudo tee /var/run/holbertonscript.pid > /dev/null
while [ $i ]
do
	echo "To infinity and beyond"
	sleep 2
	trap "echo \"I hate the kill command\"; sudo rm /var/run/holbertonscript.pid; exit" SIGTERM
	trap "echo \"Y U no love me?!\"; exit" SIGINT
	trap "sudo rm /var/run/holbertonscript.pid; exit" SIGQUIT
done
