#!/usr/bin/env bash
# Manages background process
arg=${1}
if [ "$arg" = "start" ]
then
	# run daemon
	./manage_my_process &
	# create PID file
	ps | tail -n 1 | cut -d ' ' -f 1 | sudo tee /var/run/my_process.pid > /dev/null
	# print message
	echo "manage_my_process started"
elif [ "$arg" = "stop" ]
then
	pkill -fo "manage_my_process" > /dev/null
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
elif [ "$arg" = "restart" ]
then
	pkill -fo "manage_my_process" > /dev/null
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	ps | tail -n 1 | cut -d ' ' -f 1 | sudo tee /var/run/my_process.pid > /dev/null
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi
