#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
for i in "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School" "Holberton School"
do
	echo "$i"
done
