#!/usr/bin/env bash
# Print numbers 1-20, specifying number of bad luck
I=1
while [ $I -le 20 ]
do
	echo "$I"
	case $I in
	4)
		echo "bad luck from China"
		;;
	9)
		echo "bad luck from Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	I=$((I + 1))
done
