#!/usr/bin/env bash
# reconfigure Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1	localhost/127.0.0.2	localhost/' ~/hosts.new
sed -i '1s/^/8.8.8.8	facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
