#!/usr/bin/env bash
# Run nginx as nginx user

# kill apache2 server
sudo pkill -f apache2

sleep 10

# change perms on config file
sudo chmod 777 /etc/nginx/nginx.conf

# update listening ports
sudo sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

# restart nginx
sudo -u nginx nginx
